name: Lu Chi
theme: jekyll-theme-midnight
description: Threat Architect from Nowhere
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/5080946?s=400&u=be182ac8f6c5ba0632301b2c94c2982815a046ee&v=4

markdown: kramdown

encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"


footer-links:
  email:
  github: lu-chi
  twitter: d0xy

url: https://github.com/lu-chi/lu-chi.github.io
baseurl: ""

permalink: /:title/

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  highlighter: rouge
  
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
